name: Linux Kernel Build
on:
  push:
    branches: [ linux-msft-wsl-4.19.y, linux-msft-wsl-5.4.y, linux-msft-wsl-5.10.y ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install pre-requisites
      run: sudo apt install -y build-essential flex bison libssl-dev libelf-dev bc
    - name: Retrieve version
      run: |
        echo "::set-output name=KERNEL::$(make kernelversion)"
      id: version
    - name: make
      run: make -j2 KCONFIG_CONFIG=Microsoft/config-wsl
    - name: install the modules directory
      run: sudo make modules_install
    - name: copy modules
      run: cp -f /lib/modules/`uname -r`/modules.builtin modules.builtin-neon-desktop-0
    - name: copy kernel
      run: cp -f arch/x86_64/boot/bzImage `make kernelversion`-neon-desktop-0
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.version.outputs.KERNEL }}-neon-desktop-0
        path: ${{ steps.version.outputs.KERNEL }}-neon-desktop-0
    - uses: actions/upload-artifact@v2
      with:
        name: modules.builtin-neon-desktop-0
        path: modules.builtin-neon-desktop-0
