name: Linux Kernel Build
on:
  push:
    branches: [ linux-msft-wsl-4.19.y, linux-msft-wsl-5.4.y, linux-msft-wsl-5.10.y ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install pre-requisites
      run: sudo apt install -y build-essential flex bison libssl-dev libelf-dev bc
    - name: make
      run: make -j2 KCONFIG_CONFIG=Microsoft/config-wsl
    - name: install the modules directory
      run: sudo make modules_install
    - name: install the kernel
      run: sudo make install
    - name: zip modules
      run: tar -czf modules.tgz /lib/modules/`uname -r`
    - uses: actions/upload-artifact@v2
      with:
        name: bzImage
        path: arch/x86_64/boot/bzImage
    - uses: actions/upload-artifact@v2
      with:
        name: modules.tgz
        path: modules.tgz
